apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-creator-role
rules:
- apiGroups: [""]
  resources: ["pods", 'persistentvolumeclaims']
  verbs: ["get", "list", "watch", "create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-creator-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: my-service-account  # The service account to bind to
  namespace: default        # The namespace where the service account exists
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-creator-role     # The role to bind
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
  namespace: default
